"""add form builder tables

Revision ID: 21511a338827
Revises: 6c48f0b481ee
Create Date: 2026-02-28 11:01:48.752062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21511a338827'
down_revision: Union[str, Sequence[str], None] = '6c48f0b481ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('default_sort_order', sa.Integer(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_form_sections_id'), 'form_sections', ['id'], unique=False)
    op.create_table('client_form_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_comment_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['form_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'section_id', name='uq_client_section_config')
    )
    op.create_index('idx_client_form_sections_client', 'client_form_sections', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_form_sections_id'), 'client_form_sections', ['id'], unique=False)
    op.create_table('form_fields_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('default_sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['form_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_key')
    )
    op.create_index(op.f('ix_form_fields_master_id'), 'form_fields_master', ['id'], unique=False)
    op.create_table('client_form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'field_id', name='uq_client_field_config')
    )
    op.create_index('idx_client_form_fields_client', 'client_form_fields', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_form_fields_id'), 'client_form_fields', ['id'], unique=False)
    op.drop_constraint(op.f('client_basic_details_client_id_fkey'), 'client_basic_details', type_='foreignkey')
    op.create_foreign_key(None, 'client_basic_details', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('client_pocs_client_id_fkey'), 'client_pocs', type_='foreignkey')
    op.create_foreign_key(None, 'client_pocs', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_pocs', type_='foreignkey')
    op.create_foreign_key(op.f('client_pocs_client_id_fkey'), 'client_pocs', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'client_basic_details', type_='foreignkey')
    op.create_foreign_key(op.f('client_basic_details_client_id_fkey'), 'client_basic_details', 'clients', ['client_id'], ['id'])
    op.drop_index(op.f('ix_client_form_fields_id'), table_name='client_form_fields')
    op.drop_index('idx_client_form_fields_client', table_name='client_form_fields')
    op.drop_table('client_form_fields')
    op.drop_index(op.f('ix_form_fields_master_id'), table_name='form_fields_master')
    op.drop_table('form_fields_master')
    op.drop_index(op.f('ix_client_form_sections_id'), table_name='client_form_sections')
    op.drop_index('idx_client_form_sections_client', table_name='client_form_sections')
    op.drop_table('client_form_sections')
    op.drop_index(op.f('ix_form_sections_id'), table_name='form_sections')
    op.drop_table('form_sections')
    # ### end Alembic commands ###
