"""add onboarding document tables

Revision ID: 2d141fd2099c
Revises: dd2940939e71
Create Date: 2026-02-28 16:56:36.438730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d141fd2099c'
down_revision: Union[str, Sequence[str], None] = 'dd2940939e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_document_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('client_onboarding_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['onboarding_document_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client_document', 'client_onboarding_documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_onboarding_documents_id'), 'client_onboarding_documents', ['id'], unique=False)
    op.create_index('uq_client_document', 'client_onboarding_documents', ['client_id', 'document_id'], unique=True)
    op.create_index(op.f('ix_client_domain_config_id'), 'client_domain_config', ['id'], unique=False)
    op.drop_index(op.f('idx_client_form_fields_client'), table_name='client_form_fields')
    op.create_index('idx_client_form_fields_client_id', 'client_form_fields', ['client_id'], unique=False)
    op.drop_index(op.f('idx_client_form_sections_client'), table_name='client_form_sections')
    op.create_index('idx_client_form_sections_client_id', 'client_form_sections', ['client_id'], unique=False)
    op.drop_column('client_form_sections', 'is_comment_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_form_sections', sa.Column('is_comment_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index('idx_client_form_sections_client_id', table_name='client_form_sections')
    op.create_index(op.f('idx_client_form_sections_client'), 'client_form_sections', ['client_id'], unique=False)
    op.drop_index('idx_client_form_fields_client_id', table_name='client_form_fields')
    op.create_index(op.f('idx_client_form_fields_client'), 'client_form_fields', ['client_id'], unique=False)
    op.drop_index(op.f('ix_client_domain_config_id'), table_name='client_domain_config')
    op.drop_index('uq_client_document', table_name='client_onboarding_documents')
    op.drop_index(op.f('ix_client_onboarding_documents_id'), table_name='client_onboarding_documents')
    op.drop_index('idx_client_document', table_name='client_onboarding_documents')
    op.drop_table('client_onboarding_documents')
    op.drop_table('onboarding_document_master')
    # ### end Alembic commands ###
