"""create crm migration documents

Revision ID: 3c9a4421e824
Revises: 4b54ce0752e6
Create Date: 2026-02-26 12:19:33.632916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9a4421e824'
down_revision: Union[str, Sequence[str], None] = '4b54ce0752e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_crm_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('using_crm', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('crm_name', sa.String(), nullable=True),
    sa.Column('want_data_migration', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('previous_crm_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_crm_info_id'), 'client_crm_info', ['id'], unique=False)
    op.create_table('crm_migration_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'document_type_id', name='unique_client_document')
    )
    op.create_index(op.f('ix_crm_migration_documents_id'), 'crm_migration_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_migration_documents_id'), table_name='crm_migration_documents')
    op.drop_table('crm_migration_documents')
    op.drop_index(op.f('ix_client_crm_info_id'), table_name='client_crm_info')
    op.drop_table('client_crm_info')
    # ### end Alembic commands ###
