"""add client payment provider table

Revision ID: 4eb22f367e92
Revises: 36296444939f
Create Date: 2026-02-28 17:08:42.386597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eb22f367e92'
down_revision: Union[str, Sequence[str], None] = '36296444939f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_payment_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('razorpay','easy_buzz','ezypay','hdfc','payu')", name='chk_payment_provider'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_client', 'client_payment_provider', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_payment_provider_id'), 'client_payment_provider', ['id'], unique=False)
    op.create_index('uq_client_provider', 'client_payment_provider', ['client_id', 'provider'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_client_provider', table_name='client_payment_provider')
    op.drop_index(op.f('ix_client_payment_provider_id'), table_name='client_payment_provider')
    op.drop_index('idx_payment_client', table_name='client_payment_provider')
    op.drop_table('client_payment_provider')
    # ### end Alembic commands ###
