"""lead pipeline tables

Revision ID: 6c48f0b481ee
Revises: d9136a5be20e
Create Date: 2026-02-26 15:31:38.545672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c48f0b481ee'
down_revision: Union[str, Sequence[str], None] = 'd9136a5be20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_lead_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_stage_name_per_client')
    )
    op.create_index(op.f('ix_client_lead_stages_id'), 'client_lead_stages', ['id'], unique=False)
    op.create_table('client_lead_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_tag_per_client')
    )
    op.create_index(op.f('ix_client_lead_tags_id'), 'client_lead_tags', ['id'], unique=False)
    op.create_table('client_lead_sub_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['client_lead_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'stage_id', 'name', name='uq_substage_per_stage')
    )
    op.create_index(op.f('ix_client_lead_sub_stages_id'), 'client_lead_sub_stages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_lead_sub_stages_id'), table_name='client_lead_sub_stages')
    op.drop_table('client_lead_sub_stages')
    op.drop_index(op.f('ix_client_lead_tags_id'), table_name='client_lead_tags')
    op.drop_table('client_lead_tags')
    op.drop_index(op.f('ix_client_lead_stages_id'), table_name='client_lead_stages')
    op.drop_table('client_lead_stages')
    # ### end Alembic commands ###
