"""remove hardcoded payment provider check constraint

Revision ID: a7ec8684ee1d
Revises: c1e22dbea2f8
Create Date: 2026-03-10 15:11:55.239300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ec8684ee1d'
down_revision: Union[str, Sequence[str], None] = 'c1e22dbea2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_payment_provider', 'client_payment_provider', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'chk_payment_provider',
        'client_payment_provider',
        sa.text("provider IN ('razorpay','easy_buzz','ezypay','hdfc','payu')")
    )
    # ### end Alembic commands ###
