"""create client crm info

Revision ID: b5b24b33b9ad
Revises: 413827b2a1a3
Create Date: 2026-02-26 11:25:38.098726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b24b33b9ad'
down_revision: Union[str, Sequence[str], None] = '413827b2a1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_crm_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('using_crm', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('crm_name', sa.String(), nullable=True),
    sa.Column('want_data_migration', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('previous_crm_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_crm_info_id'), 'client_crm_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_crm_info_id'), table_name='client_crm_info')
    op.drop_table('client_crm_info')
    # ### end Alembic commands ###
