"""add payment provider master

Revision ID: c1e22dbea2f8
Revises: 2d8631585718
Create Date: 2026-03-10 14:58:04.744229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1e22dbea2f8'
down_revision: Union[str, Sequence[str], None] = '2d8631585718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_provider_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_payment_provider_master_id'), 'payment_provider_master', ['id'], unique=False)
    # ### end Alembic commands ###

    # Seed data
    master_table = sa.table(
        'payment_provider_master',
        sa.column('code', sa.String),
        sa.column('display_name', sa.String),
        sa.column('required_fields', postgresql.JSONB),
        sa.column('is_active', sa.Boolean)
    )

    op.bulk_insert(
        master_table,
        [
            {
                "code": "razorpay",
                "display_name": "Razorpay",
                "required_fields": [
                    "razorpay_api_key",
                    "key_name",
                    "partner",
                    "x_razorpay_account",
                    "verify_url",
                    "auth_key",
                    "razorpay_secret",
                    "order_url"
                ],
                "is_active": True
            },
            {
                "code": "easy_buzz",
                "display_name": "Easy Buzz",
                "required_fields": [
                    "merchant_key",
                    "merchant_salt",
                    "base_url",
                    "environment",
                    "retrieve_url"
                ],
                "is_active": True
            },
            {
                "code": "ezypay",
                "display_name": "Ezypay",
                "required_fields": [
                    "merchant_id",
                    "encryption_key",
                    "base_url",
                    "verify_url"
                ],
                "is_active": True
            },
            {
                "code": "hdfc",
                "display_name": "HDFC",
                "required_fields": [
                    "merchant_id",
                    "customer_id",
                    "key",
                    "base_url",
                    "environment",
                    "retrieve_url"
                ],
                "is_active": True
            },
            {
                "code": "payu",
                "display_name": "PayU",
                "required_fields": [
                    "retrieve_url",
                    "merchant_key",
                    "merchant_salt"
                ],
                "is_active": True
            }
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_provider_master_id'), table_name='payment_provider_master')
    op.drop_table('payment_provider_master')
    # ### end Alembic commands ###
