"""create client tentetive counts table

Revision ID: e2765f284028
Revises: 8f784f666d31
Create Date: 2026-02-25 16:50:09.383813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2765f284028'
down_revision: Union[str, Sequence[str], None] = '8f784f666d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_integrations_master_id'), 'integrations_master', ['id'], unique=False)
    op.create_table('client_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations_master.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'integration_id', name='unique_client_integration')
    )
    op.create_index(op.f('ix_client_integrations_id'), 'client_integrations', ['id'], unique=False)
    op.create_table('client_tentative_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('lead_intake', sa.Integer(), server_default='0', nullable=False),
    sa.Column('application_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('raw_data_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('crm_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('widget_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('application_count >= 0', name='check_application_non_negative'),
    sa.CheckConstraint('crm_count >= 0', name='check_crm_non_negative'),
    sa.CheckConstraint('lead_intake >= 0', name='check_lead_intake_non_negative'),
    sa.CheckConstraint('raw_data_count >= 0', name='check_raw_data_non_negative'),
    sa.CheckConstraint('widget_count >= 0', name='check_widget_non_negative'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_tentative_counts_id'), 'client_tentative_counts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_tentative_counts_id'), table_name='client_tentative_counts')
    op.drop_table('client_tentative_counts')
    op.drop_index(op.f('ix_client_integrations_id'), table_name='client_integrations')
    op.drop_table('client_integrations')
    op.drop_index(op.f('ix_integrations_master_id'), table_name='integrations_master')
    op.drop_table('integrations_master')
    # ### end Alembic commands ###
